DROP DATABASE IF EXISTS tinyuser CASCADE;
CREATE DATABASE IF NOT EXISTS tinyuser;
SET DATABASE = tinyuser;

CREATE TABLE IF NOT EXISTS users (
    id SERIAL NOT NULL PRIMARY KEY,
    email VARCHAR UNIQUE NOT NULL,
    username VARCHAR UNIQUE NOT NULL
);
